### ISSUE TITLE
Camera hang

### ISSUE THREAD

**Issue by ngoquang2708** [ngoquang2708/android_device_samsung_vivalto3gvn#100]

**Comment by diepquynh** [comment]
This is caused by gralloc mapper

**Comment by ngoquang2708** [comment]
Do you know how to fix it?
null

**Comment by diepquynh** [comment]
We can build mapper HAL for the camera, but instead screenshots can't be captured with the HAL

**Comment by diepquynh** [comment]
Permanent solution will be fixing gralloc for HIDL compatible, which isn't solved

**Comment by ngoquang2708** [comment]
I am working on rewritting of gralloc in N.

**Comment by diepquynh** [comment]
Great. All hopes put on you

**Comment by ngoquang2708** [comment]
Maybe #110 causes this issue.

**Comment by ngoquang2708** [comment]
Commit https://github.com/ngoquang2708/android_hardware_sprd/commit/2ce3d20e4581ce015f2c7a8f96e59877343e4feb seem to solve this.
