### ISSUE TITLE
Cannot play video

### ISSUE THREAD

**Issue by ngoquang2708** [ngoquang2708/android_device_samsung_vivalto3gvn#108]

**Comment by diepquynh** [comment]
It's fine playing here
Do you have logs?

**Comment by ngoquang2708** [comment]
Its here: https://gist.github.com/ngoquang2708/a6777ad7464c8ca1106470621a707f0f.
Do I need to update xml config?

**Comment by diepquynh** [comment]
I think there's an unsupported codec in your configs
`07-11 21:20:05.037   184  1781 E ACodec  : Unable to instantiate a decoder for type 'audio/mp4a-latm' with err 0xfffffffe.`

**Comment by diepquynh** [comment]
Try to have a check on boot, see whether sprd OMX codecs are initialized or not

**Comment by ngoquang2708** [comment]
Wait. Is ffmpeg removed?

**Comment by diepquynh** [comment]
Maybe. I can't see it in my system

**Comment by ngoquang2708** [comment]
Aghh. I have included it in my ```media_codecs.xml```. That why codecs is failed to init. I have just removed it. Music is working now. Still no video though.

**Comment by ngoquang2708** [comment]
New logcat after removed ffmpeg xml: https://gist.github.com/ngoquang2708/2d410d8a7a1d146982cf69c1d9592620.

**Comment by diepquynh** [comment]
First is that why it's using SW decoder instead of HW one 😕 
Second, you need to disable treble OMX: `persist.media.treble_omx=false`
`07-11 21:56:02.949   187  1834 I OMXClient: Treble IOmx obtained`
We don't support binderized OMX codecs, as we don't have Oreo widevine blobs for it

**Comment by ngoquang2708** [comment]
You have go all through this, right :D

**Comment by diepquynh** [comment]
Yeah, since first LOS 15.0 releases :v

**Comment by ngoquang2708** [comment]
Fixed by https://github.com/ngoquang2708/android_device_samsung_vivalto3gvn/commit/f8cf92ac8910b0ba830bae1273b463e5280239c6 and https://github.com/ngoquang2708/android_device_samsung_vivalto3gvn/commit/f5da1991a0f396c51b67c0061db113fd4b6c7aa9.
