### ISSUE TITLE
cm-12.1: 2nd SIM not work

### ISSUE THREAD

**Issue by ngoquang2708** [ngoquang2708/android_device_samsung_vivalto3gvn#11]
When enable DSDS ril mode, both SIMs die. Remove it, 1st SIM works fine.

**Comment by diepquynh** [comment]
Actually it still works, but for some reason, RIL crashes when enabling mobile data

**Comment by ngoquang2708** [comment]
I remove dsds to use single sim and it works. Call, ussd...

**Comment by ngoquang2708** [comment]
@koquantam I tried remove ril class from `system.prop` and `BoardConfig.mk` but 2nd SIM still not work.

**Comment by ngoquang2708** [comment]
Haha, got a fix, need to confirm it myself :)

**Comment by diepquynh** [comment]
RIL class is mandatory tho, removing it give you no access to RIL

**Comment by diepquynh** [comment]
I mean calls, SMS, mobile data, etc

**Comment by diepquynh** [comment]
What's your solution about RIL?

**Comment by ngoquang2708** [comment]
You already known it, changing ril socket names. Got 2 signal now, no mobile data, same imei for both sim.

**Comment by diepquynh** [comment]
IDK why those weird things happen with you. I still get both IMEIs and signals in proper way, but no mobile data only (chosen RIL crashes when enable mobile data for chosen SIM)

**Comment by diepquynh** [comment]
By seeing logcat, there're such things like "accept_ra_rt_table" and "use_optimistic" thingies. Just wondering what are they

**Comment by ngoquang2708** [comment]
Confirmed that RIL crashes when enable mobile data for chosen SIM.

**Comment by ngoquang2708** [comment]
Fixed by c5ac459449fcc1ff67df606124d9453fa243928e.

**Comment by diepquynh** [comment]
Please rename the issue and re-open it

**Comment by ngoquang2708** [comment]
What is the name it should be and why re-open it?

**Comment by diepquynh** [comment]
Hmm... 1st mobile data doesn't work, then re-open it as a new issue

**Comment by ngoquang2708** [comment]
We are tracking it in #25, aren't we?

**Comment by diepquynh** [comment]
Uhh... ok, my mistake :/
