### ISSUE TITLE
IptablesRestoreController failed

### ISSUE THREAD

**Issue by ngoquang2708** [ngoquang2708/android_device_samsung_vivalto3gvn#117]
Log: https://gist.github.com/ngoquang2708/190e863a7a2700459028e92102bf1ef5.

**Comment by ngoquang2708** [comment]
All tethering issues seem relate to this issue.

**Comment by diepquynh** [comment]
You need these:
CONFIG_IP_NF_MATCH_RPFILTER=y
CONFIG_IP6_NF_MATCH_RPFILTER=y

**Comment by ngoquang2708** [comment]
Hope it works.

**Comment by diepquynh** [comment]
This is the solution that works since N. On O idk what about old bcm4343 kernel, but mine doing weird stuffs. WiFi Tethering just work as placebo (it can be turned on, but give no hotspot signals). Maybe some kernel-related commits needed again?

**Comment by ngoquang2708** [comment]
Me too. It can turn on, but no ssid found by other device, and logcat shows error related to iptables. Then the UI show Error under the turn hotspot on switch.

**Comment by diepquynh** [comment]
If it shows error, then these 2 configs enabled will do their jobs, but if it doesn't show error (just keep turning on only, like my situation) then it's a different thing

**Comment by ngoquang2708** [comment]
OK. Guess what, I am in the same situation as you now.
But now bluetooth tethering works!

**Comment by diepquynh** [comment]
USB tethering will work also. Tested on my W10 PC

**Comment by ngoquang2708** [comment]
My USB seems not to work like expected. No MTP, so no tethering.

**Comment by ngoquang2708** [comment]
IptablesRestoreController failure is still appear after reboot. But not when enable or disable tethering.
Edit: tethering is still work of-course.

**Comment by ngoquang2708** [comment]
So I think the invisible SSID is related to hostapd.

**Comment by ngoquang2708** [comment]
Fixed by commit https://github.com/ngoquang2708/android_kernel_samsung_vivalto3gvn/commit/39d9f1fdf48e145866aee0fbf7a950edb89a8aee.

**Comment by diepquynh** [comment]
LOL just about to comment on the issue you pinged me
