### ISSUE TITLE
cm-12.1: Audio FX has no effect

### ISSUE THREAD

**Issue by ngoquang2708** [ngoquang2708/android_device_samsung_vivalto3gvn#14]

**Comment by ngoquang2708** [comment]
NuPlayer again.

**Comment by ngoquang2708** [comment]
Everything will be working normally when switch to AwesomePlayer in DevSettings.

**Comment by diepquynh** [comment]
Did your phone freezes when pressing volume buttons?

**Comment by diepquynh** [comment]
Not exactly freezes, but Trebuchet freezes, and after a couple of minutes, it soft-reboot

**Comment by ngoquang2708** [comment]
It is working normally.

**Comment by diepquynh** [comment]
After turning to AwesomePlayer?

**Comment by ngoquang2708** [comment]
Both NP and AP.

**Comment by ngoquang2708** [comment]
Any logcat?

**Comment by diepquynh** [comment]
I can't get it now, but it shows that "service media.audio_flinger died" then soft-reboot
Pressing volume buttons makes Trebuchet freezes. Audio settings in Settings does the same thing, can't change audio volume

**Comment by diepquynh** [comment]
Btw, can i try your build?

**Comment by ngoquang2708** [comment]
I am building it currently with major bug fix with libatchannel which fix audio routing to ext speaker when incall. you can try my old build [cm-12.1-20160226-UNOFFICIAL-vivalto3gvn.zip](http://qrpi.noip.me:10080/upload/cm-12.1-20160226-UNOFFICIAL-vivalto3gvn.zip)

**Comment by ngoquang2708** [comment]
About crashing mediaserver, I didn't remember exactly, when change it user to `root` instead of `media` in `init.rc`, crashing is gone. Our audio HAL require more privilege than standard one.

**Comment by ngoquang2708** [comment]
May be `system` user should be enough but I haven't tried it.

**Comment by diepquynh** [comment]
We need that on CM12.1. Stock APM in CM11 makes UI audio very quiet, but media or ringtone works fine

**Comment by ngoquang2708** [comment]
OK, I remember it now. I removed `nvram ccci` groups plus set user to `root` and `mediaserver` audio service stop crashing.

**Comment by ngoquang2708** [comment]
I don't know why but audio in cm12 is perfectly, not very loud like in cm11, no audio blobs here.

**Comment by ngoquang2708** [comment]
@koquantam I remembered that your cm12.1 build has both sim work, right?

**Comment by diepquynh** [comment]
Only calls, SMS. Mobile data works only for one SIM

**Comment by ngoquang2708** [comment]
But you could see 2 network signals?

**Comment by diepquynh** [comment]
Yes and 2 exclamation marks on both SIMs, which means no mobile data for almost all of the time. If enabling mobile while in dual-SIM mode, that chosen SIM RIL would crash

**Comment by ngoquang2708** [comment]
@koquantam Oh god, at least dual-SIM work for you, never work for me. When I enable `dsds`, both network signal is gone but 1st SIM is usable. Could you try to flash my new build to see if `dsds` work (please re-enable it from `build.prop`).

@Y300-0100 If you cannot wait, try this.

Here is it: [cm-12.1-20160228-UNOFFICIAL-vivalto3gvn.zip](http://qrpi.noip.me:10080/upload/cm-12.1-20160228-UNOFFICIAL-vivalto3gvn.zip)

**Comment by diepquynh** [comment]
@ngoquang2708 
vivalto3gvn build cannot work on kanas, as they had different hardware

**Comment by ngoquang2708** [comment]
I though he had galaxy v.

**Comment by diepquynh** [comment]
He has mentioned that he was working for G355HN, Galaxy Core 2 with NFC

**Comment by diepquynh** [comment]
Did you integrated libmemoryheapion?

**Comment by ngoquang2708** [comment]
Not yet. Using `LD_PRELOAD` is just a hack, much like we are hacking `libbinder` right now. If we can make camera codes to work, then we can use `libmemoryheapion` without `LD_PRELOAD` hacking and `libbinder` hacking too.

**Comment by diepquynh** [comment]
Bro, not just camera relies on ION. Anything on HW needs ION too, so just make it temporary hack instead. People want a lollipop build instead of a bugless build

**Comment by ngoquang2708** [comment]
Of course, when camera source codes work, we can change hwc source code or any other source code to use `libmemoryheapion`!

**Comment by ngoquang2708** [comment]
And the current hack on libbinder is working, bro!

**Comment by diepquynh** [comment]
Yes, it's working
Dual-SIM seems broken. Could you try removing RIL CFLAGS?
More weird is: SIM1 can call, but SIM2 can't. Starting to have some headaches

**Comment by ngoquang2708** [comment]
You said Dual-SIM is broken, so SIM2 supported to not work?!?!?

**Comment by diepquynh** [comment]
"supposed" , not "supported" dude
Yes, i've some typos :D

**Comment by ngoquang2708** [comment]
Yes, my grammar it not good. Thanks for pointing it out any way :D
