### ISSUE TITLE
cm-12.1: YouTube app cannot play video

### ISSUE THREAD

**Issue by ngoquang2708** [ngoquang2708/android_device_samsung_vivalto3gvn#15]
It just produce some sounds but the video won't move.

**Comment by thanhthuy89** [comment]
edit buildprop 5.1.1 to 4.4.2 or 4.4.4

**Comment by ngoquang2708** [comment]
@thanhthuy89  I will try.

**Comment by thanhthuy89** [comment]
when I delete fonts from theme by root explorer that it will does not have hanging logo status

**Comment by thanhthuy89** [comment]
bug from font

**Comment by ngoquang2708** [comment]
YouTube crashes mediaserver when it tries to load DRM plugins.

**Comment by ngoquang2708** [comment]
And DRM plugins are failed to load in CM12.1. How on CM11.0?

**Comment by ngoquang2708** [comment]
OMG I can play 144p video :))

**Comment by ngoquang2708** [comment]
ZingMp3 can play 720p =))

**Comment by ngoquang2708** [comment]
@koquantam Did you try to plauy video in ZingMP3? Why Zing MP3 can play videos, even 720p, while YT cannot :(

**Comment by diepquynh** [comment]
The strange guy on XDA said that he disabled HW rendering and YT works. I haven't tested it yet

**Comment by ngoquang2708** [comment]
Fixed by a093f22e2aa7207b756afee27989ea6dfbea4b5d.
