### ISSUE TITLE
cm-12.1: camera is crashed when switch from recording mode to capture mode

### ISSUE THREAD

**Issue by ngoquang2708** [ngoquang2708/android_device_samsung_vivalto3gvn#16]
After that, Torch stops working.

**Comment by diepquynh** [comment]
How the hell you got camera working?

**Comment by diepquynh** [comment]
I'm pretty damn crazy with these stuffs in CM12.1

**Comment by ngoquang2708** [comment]
Use these [patches](https://github.com/ngoquang2708/android_device_samsung_vivalto3gvn/tree/cm-12.1/patches) and my cm-12.1 branch.

**Comment by ngoquang2708** [comment]
@koquantam Why don't you make cm-12.1 branch from cm-11.0 branch so that I could send pull requests.

**Comment by diepquynh** [comment]
Well, i want to get rid of those source building, since my machine is not so powerful as your. CM12.1 takes so damn long even with prebuilt chromium because of my dual-core CPU

**Comment by ngoquang2708** [comment]
What do you means `those source building`? Didn't you just build it? Building cm-12.1 is nothing to do with git history, I just want to keep it so that I and you have the same git history, and sync our changes.

**Comment by diepquynh** [comment]
Oops, sorry for typos :D
I mean that the vendor sources (libs in our device repo). About changes, should we make a team? It's better than sending pull requests

**Comment by ngoquang2708** [comment]
OK, what will be the name? I cannot think out any name :D

**Comment by diepquynh** [comment]
Build 20160228 doesn't exist anymore

**Comment by ngoquang2708** [comment]
Maybe this commit 6dea3064fd7403875223a97226e317b0a842739b solves it.
