### ISSUE TITLE
cm-12.1: Chrome cannot play YouTube video while built-in Browser can

### ISSUE THREAD

**Issue by ngoquang2708** [ngoquang2708/android_device_samsung_vivalto3gvn#17]

**Comment by diepquynh** [comment]
Did you checked with internal player (Gallery)

**Comment by ngoquang2708** [comment]
They just work fine when enable Awesome player in DevSettings since our
codecs blob is not work with default NuPlayer. But not with Chrome in
YouTube. Chrome can play video from some site like vnexpress.net.

**Comment by ngoquang2708** [comment]
It seems that built-in Browser use software decoding (Google VP9 decoder) to decode video. Not tested on Chrome.

**Comment by ngoquang2708** [comment]
Voi nhieu loi nua.

**Comment by diepquynh** [comment]
LOL

**Comment by ngoquang2708** [comment]
Shit :(

**Comment by ngoquang2708** [comment]
OK, Chrome can use Google's VP9 decoder to play YT now. But SPRD desn't have HW VP9 decoder, just VP8. So sadly!

**Comment by diepquynh** [comment]
Weird. Why KK can play YT videos?

**Comment by ngoquang2708** [comment]
I want to know :D
