### ISSUE TITLE
cm-12.1: Bootloop when changing font

### ISSUE THREAD

**Issue by diepquynh** [ngoquang2708/android_device_samsung_vivalto3gvn#21]
Again, a person reported

**Comment by ngoquang2708** [comment]
Confirmed. Looking for solution.

**Comment by diepquynh** [comment]
Somehow the Typeface API can't access the fonts.xml in /data/system/theme/fonts. It gives EACCES signal (access denied)

**Comment by ngoquang2708** [comment]
CM12.1 is EOL.

**Comment by diepquynh** [comment]
It's itself a common problem. Must be closed before
