### ISSUE TITLE
CM11 : error compile SamsungSPRDRIL.java

### ISSUE THREAD

**Issue by cleverior** [ngoquang2708/android_device_samsung_vivalto3gvn#23]
here the logcat

> frameworks/opt/telephony/../../../device/samsung/vivalto3gvn/ril/com/android/internal/telephony/SamsungSPRDRIL.java:45: error: constructor RIL in class RIL cannot be applied to given types;
>         super(context, networkMode, cdmaSubscription, instanceId);
>         ^
>   required: Context,int,int
>   found: Context,int,int,Integer
>   reason: actual and formal argument lists differ in length
> frameworks/opt/telephony/../../../device/samsung/vivalto3gvn/ril/com/android/internal/telephony/SamsungSPRDRIL.java:85: error: cannot find symbol
>             if (mSubscriptionStatusRegistrants != null) {
>                 ^
>   symbol:   variable mSubscriptionStatusRegistrants
>   location: class SamsungSPRDRIL
> frameworks/opt/telephony/../../../device/samsung/vivalto3gvn/ril/com/android/internal/telephony/SamsungSPRDRIL.java:86: error: cannot find symbol
>                 mSubscriptionStatusRegistrants.notifyRegistrants(
>                 ^
>   symbol:   variable mSubscriptionStatusRegistrants
>   location: class SamsungSPRDRIL
> frameworks/opt/telephony/../../../device/samsung/vivalto3gvn/ril/com/android/internal/telephony/SamsungSPRDRIL.java:91: error: cannot find symbol
>             if (mSubscriptionStatusRegistrants != null) {
>                 ^
>   symbol:   variable mSubscriptionStatusRegistrants
>   location: class SamsungSPRDRIL
> frameworks/opt/telephony/../../../device/samsung/vivalto3gvn/ril/com/android/internal/telephony/SamsungSPRDRIL.java:92: error: cannot find symbol
>                 mSubscriptionStatusRegistrants.notifyRegistrants(
>                 ^
>   symbol:   variable mSubscriptionStatusRegistrants
>   location: class SamsungSPRDRIL
> frameworks/opt/telephony/../../../device/samsung/vivalto3gvn/ril/com/android/internal/telephony/SamsungSPRDRIL.java:99: error: cannot find symbol
>         int simId = mInstanceId == null ? 0 : mInstanceId;
>                     ^
>   symbol:   variable mInstanceId
>   location: class SamsungSPRDRIL
> frameworks/opt/telephony/../../../device/samsung/vivalto3gvn/ril/com/android/internal/telephony/SamsungSPRDRIL.java:99: error: cannot find symbol
>         int simId = mInstanceId == null ? 0 : mInstanceId;
>                                               ^
>   symbol:   variable mInstanceId
>   location: class SamsungSPRDRIL
> frameworks/opt/telephony/../../../device/samsung/vivalto3gvn/ril/com/android/internal/telephony/SamsungSPRDRIL.java:114: error: cannot find symbol
>             if (mInstanceId != null) {
>                 ^
>   symbol:   variable mInstanceId
>   location: class SamsungSPRDRIL
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 8 errors

**Comment by ngoquang2708** [comment]
Please compare your ril class with mine.

**Comment by ngoquang2708** [comment]
Why don't you just fork my repo or @koquantam repo, instead of doing your
own repo and report errors here?

**Comment by cleverior** [comment]
which repo ? i've replace all of your repo and from koquantam. but still get error when compiling ril. i dont know why. maybe this is bcz im using source CM from high compresed without .repo. So, my source is out of date.

**Comment by ngoquang2708** [comment]
I can compress my CM sources and send you if you wish.

**Comment by ngoquang2708** [comment]
I've checked. Your source tree is out of date compare to my device source tree.

**Comment by cleverior** [comment]
Yes if you dont mind. Btw, have you check your email and PM xda ? i've sent invitation to your email.

**Comment by ngoquang2708** [comment]
Checked. Accepted :D

**Comment by ngoquang2708** [comment]
Use this [cm-11.0.7z.torrent.zip](https://github.com/ngoquang2708/android_device_samsung_vivalto3gvn/files/167298/cm-11.0.7z.torrent.zip) to download cm-11.0 source (about 2.82GiB). I am seeding it from my tiny home server (R.Pi).

**Comment by ngoquang2708** [comment]
I can see that download speed is slow, you can try [this](http://qrpi.noip.me:10080/upload/cm-11.0.7z) to see if it is faster.

**Comment by ngoquang2708** [comment]
I have a question, I am already a member vivalto group, so do I have write permissions to its repositories?

**Comment by diepquynh** [comment]
Yes, you do
I can fork my project there

**Comment by ngoquang2708** [comment]
Still no write access.

**Comment by ngoquang2708** [comment]
OK, found it, I just can send PR https://help.github.com/articles/permission-levels-for-an-organization/

**Comment by cleverior** [comment]
thanks bro. direct link is better than torrent for me. :D

**Comment by ngoquang2708** [comment]
I though they're the same. Both from my tiny server!

**Comment by ngoquang2708** [comment]
You can remove the kernel and the device tree, then clone git repo to get updates.

**Comment by cleverior** [comment]
ok. could u compress your cm12 source also ? thanks in advance.

**Comment by ngoquang2708** [comment]
Yes

**Comment by ngoquang2708** [comment]
@cleverior Again, 2 methods to download:
- [Torrent](https://github.com/ngoquang2708/android_device_samsung_vivalto3gvn/files/173781/cm-12.1.7z.torrent.zip)
- [Direct](http://qrpi.noip.me:10080/upload/cm-12.1.7z)

**Comment by cleverior** [comment]
@ngoquang2708 i cant download from direct link bro. could you check your mini server ?

**Comment by ngoquang2708** [comment]
It is operating normally. What's error? Please check again.

**Comment by ngoquang2708** [comment]
I recommend torrent. It is slow at first, but it is safer with more integrity checking.

**Comment by cleverior** [comment]
it cant start download. even using IDM.

**Comment by ngoquang2708** [comment]
IDM will kill my server! Use browser please!

**Comment by cleverior** [comment]
and there is error "Cannot download the file because of timeout. Cannot connect to qrpi.noip.me:10080"

**Comment by ngoquang2708** [comment]
OK, use my IP instead: 14.187.49.86

**Comment by ngoquang2708** [comment]
You can ping qrpi.noip.me to see if it is the same like my IP :D

**Comment by cleverior** [comment]
username and passwd ?

**Comment by ngoquang2708** [comment]
You know, cheap internet sub w/ dynamic IP :D

**Comment by ngoquang2708** [comment]
What username???

**Comment by ngoquang2708** [comment]
http://14.187.49.86:10080/upload/cm-12.1.7z

**Comment by ngoquang2708** [comment]
That IP will change.

**Comment by cleverior** [comment]
This site can’t be reached
14.187.49.86 took too long to respond.
ERR_CONNECTION_TIMED_OUT

:(

**Comment by ngoquang2708** [comment]
What about this: http://14.187.49.86:10080/?

**Comment by cleverior** [comment]
still get the same error

**Comment by ngoquang2708** [comment]
Aghh, Firewall???????????????
Could you try torrent?

**Comment by cleverior** [comment]
still "connecting to peers 0.0%" since yesterday

**Comment by cleverior** [comment]
i've disable my firewall

**Comment by ngoquang2708** [comment]
OK, I will try another HTTP port :(

**Comment by ngoquang2708** [comment]
What is the ip when u ping qrpi.noip.me?

**Comment by cleverior** [comment]
thanks in advance. sorry if i disturbing your time.

**Comment by cleverior** [comment]
14.187.49.86

**Comment by ngoquang2708** [comment]
OK, try to connect to it through port 54455

**Comment by ngoquang2708** [comment]
Any ideas about file sharing services???

**Comment by cleverior** [comment]
still cant connect. could you upload it to google drive ?

**Comment by ngoquang2708** [comment]
OK.

**Comment by ngoquang2708** [comment]
I will send you the link about 2 hours later.

**Comment by cleverior** [comment]
OK. Thanks again.

**Comment by ngoquang2708** [comment]
I bet ISP block your incoming connection :D

**Comment by diepquynh** [comment]
You know, his country is very far from our city, so it can't reach us. Also you're using mobile ISP, which has limited connection, so how can he download your source properly?

**Comment by ngoquang2708** [comment]
I use FTTH, up/down -> 20Mbps/20Mbps, not bad!

**Comment by cleverior** [comment]
I can download cm11 from direct link that shared by ngoquang. But why i
cant do the same thing with cm12.1 link ?

**Comment by ngoquang2708** [comment]
@cleverior Can you download cm-11.0 link right now :D?

**Comment by ngoquang2708** [comment]
@cleverior Do you compile cm-11.0 successfully? If it is, please close this issue!

**Comment by ngoquang2708** [comment]
@cleverior Link Link https://drive.google.com/file/d/0B81z8fcTnClGN2NIbVFkWVZNbkE/view?usp=sharing

**Comment by cleverior** [comment]
i just download the source. not try to build yet. I'll try to build later if i have free time. Btw, thanks for help me. You can delete all the links.
