### ISSUE TITLE
cm-12.1: Settings is crashed if we select Backup & Reset

### ISSUE THREAD

**Issue by ngoquang2708** [ngoquang2708/android_device_samsung_vivalto3gvn#24]

**Comment by thanhthuy89** [comment]
remove Backup & Reset

**Comment by ngoquang2708** [comment]
@thanhthuy89 If you have free time, please test and report issues here, thank you!

**Comment by thanhthuy89** [comment]
bugs 
theme (bootloop)
video codec
video : record green
dual sim (not so important)
Boot and install the application so long
finish

**Comment by thanhthuy89** [comment]
ấn nut đa nhiệm cả buổi ứng dụng gần đây mới xuất hiện . fix nó

**Comment by ngoquang2708** [comment]
Lack of Gapps causes this issue.
