### ISSUE TITLE
cm-12.1: randomly shows "SIM cards changed" at startup

### ISSUE THREAD

**Issue by ngoquang2708** [ngoquang2708/android_device_samsung_vivalto3gvn#31]

**Comment by diepquynh** [comment]
You can close this, that doesn't exist
Btw, RIL signals seems buggy. We have internet access directly, but it shows exclamation marks

**Comment by ngoquang2708** [comment]
I don't know, I had it before, now it is gone!!??
About RIL signal, You got it when you turn mobile data on or off?

**Comment by diepquynh** [comment]
After turning off WiFi, it acts like that

**Comment by diepquynh** [comment]
But still have internet access
Another mention: Only like that when wifi's connected, else doesn't

**Comment by ngoquang2708** [comment]
It seems it is related to service provider.
I have another problem, when making a call, one sim doesn't have sound, I've to hang up and try again, the other sim doesnt have that. When swap sim slots, still have problem with that sim. So service provider case troubles here.

**Comment by diepquynh** [comment]
Maybe

**Comment by diepquynh** [comment]
Well, that's my fault after sharing the ROM on tinhte. Now Vietnamese everywhere :D

**Comment by ngoquang2708** [comment]
:D

2016-03-22 22:18 GMT+07:00 Quyền notifications@github.com:

**Comment by ngoquang2708** [comment]
Still persist, but randomly though.

**Comment by diepquynh** [comment]
Check your SIM card pins
Maybe they're dirty

**Comment by ngoquang2708** [comment]
Haha, that a trick.

2016-03-26 22:12 GMT+07:00 Quyền notifications@github.com:

**Comment by ngoquang2708** [comment]
CM12.1 is EOL.
