### ISSUE TITLE
cm-12.1: Spamming logcat?

### ISSUE THREAD

**Issue by diepquynh** [ngoquang2708/android_device_samsung_vivalto3gvn#35]
Logcat keep giving this line:
`D/audio_hw_primary( 2286): into in_read1: start: in->is_voip is 0, voip_state is 0 in_devices is 80000004
`

**Comment by ngoquang2708** [comment]
That logcat show when there is something use the mic.

**Comment by diepquynh** [comment]
Umm... Weird. It doesn't like that before
Did you added debugging flag to audio driver?

**Comment by ngoquang2708** [comment]
CM12.1 is EOL.
