### ISSUE TITLE
cm-13.0: fstab rework

### ISSUE THREAD

**Issue by diepquynh** [ngoquang2708/android_device_samsung_vivalto3gvn#38]
Yes, since changes in Marshmallow, so storage depends on fstab a lot
storage_list.xml now useless (removed from framework code)
Also, external fstab need this flag to be used by adoptable storage: encryptable=userdata
See here: https://source.android.com/devices/storage/config.html

**Comment by ngoquang2708** [comment]
Updated c7c99c2c019a700637560177122064951685a9a1.
About adoptable storage, I will do it later when the device successfully booted. Currently, it cannot boot at all, just reboot to recovery.

**Comment by diepquynh** [comment]
SELinux also needs to be updated, in kernel implementations, because it's now in Android mainline

**Comment by diepquynh** [comment]
Can you give me the ROM zip?

**Comment by ngoquang2708** [comment]
I think it is useless now. No Boot animation, no logcat, nothing.

**Comment by diepquynh** [comment]
Reboots straight to recovery?

**Comment by ngoquang2708** [comment]
Yes

**Comment by ngoquang2708** [comment]
CM 13.0 supports radio?!!

**Comment by ngoquang2708** [comment]
Any idea on how to get system logs (dmesg, logcat) when the device auto reboot to recovery mode?

**Comment by diepquynh** [comment]
Nope, you can't
At least it must shows the boot animation OR screen lowers the light (decompressing kernel completed) then you can get dmesg or logcat

**Comment by diepquynh** [comment]
Umm... radio? Which app?

**Comment by ngoquang2708** [comment]
It is good if I have UART, even I don't know what is is :D

**Comment by ngoquang2708** [comment]
I can see it compiles some codes have `radio` word.

**Comment by diepquynh** [comment]
You just need a cable, because you've a Raspberry Pi right? It can do UART jobs

**Comment by ngoquang2708** [comment]
Doesn't have any experience with this UART thing.

**Comment by diepquynh** [comment]
I guess you shouldn't touch this if you don't want everything end up in pain :D

**Comment by ngoquang2708** [comment]
OK

**Comment by ngoquang2708** [comment]
It just stop here: https://github.com/ngoquang2708/android_system_core/blob/cm-13.0/init/init.cpp#L988, cannot go further :(
Failed to load selinux policy.

**Comment by ngoquang2708** [comment]
OK, It seems that the kernel do not know the format of the new `sepolicy` file which is generated by CM-13.0. I use the one in `rootdir` and the device now stuck at SS logo, not auto reboot any more. Still no logcat.

**Comment by diepquynh** [comment]
There still lots of if conditions that triggers security_failure() command, including restorecon("/init"), write("...checkreqprot"...)
https://github.com/ngoquang2708/android_system_core/blob/cm-13.0/init/init.cpp#L994
Let's see if this kernel patch work for you:
https://github.com/SandPox/android_kernel_samsung_kyleproxx/commit/0fe93a236f1d35875310b6bde82621ac58ae298e

**Comment by Qiangong2** [comment]
I'm having the same issue with my cm13 build for samsung galaxy star pro S7262 (logan2g)

**Comment by diepquynh** [comment]
@ngoquang2708 Bro, I think we should use CM12.1's init binary instead

**Comment by diepquynh** [comment]
CM13's init binary got fvcked up

**Comment by Qiangong2** [comment]
@koquantam the patch you linked to before doesn't work

**Comment by diepquynh** [comment]
@Qiangong2 Can you be able to get logcat?

**Comment by Qiangong2** [comment]
@koquantam it doesn't even build

**Comment by ngoquang2708** [comment]
Anyone know how to use UART. I planned to buy a UART to USB convert to debug the kernel. It is CP2012. It should be Bus Pirate but the CP2012 is just about $3, Bus Pirate is $40 and I cannot effort. Then we need to probe the UART location in the phone main board. But one thing make I afraid is that what is the console name the phone use to direct its output to. proberly `/dev/ttyS1` but while the phone is running, `/proc/cmdline` doesn't have it.

**Comment by diepquynh** [comment]
Well, I don't think our country has those UART thingy, because it's not popular here
Anyway, how do you build kernel first in CM source?

**Comment by ngoquang2708** [comment]
@koquantam Are you kidding man, we have tons of it [here](http://hshop.vn/products/mach-chuyen-usb-uart-cp2102).
To build the kernel first, run `make bootimage`. Do not use any commands that use parallel building like `make -jX` or `mka`.

**Comment by ngoquang2708** [comment]
BONUS: I broke my softkeys while opening the screen, such a genius.

**Comment by diepquynh** [comment]
LOL, the whole mainboard is glued, not screws

**Comment by diepquynh** [comment]
Just reconnect the connection cable

**Comment by ngoquang2708** [comment]
Did it many times but didn't help, using your `qemu.hw.mainkeys=0` trick.

**Comment by ngoquang2708** [comment]
Cannot locate the UART location on the board :(

**Comment by ngoquang2708** [comment]
@Qiangong2 Maybe one of these commits will help you: revert [this](https://github.com/ngoquang2708/android_system_core/commit/bbc01d825448a738160716f95d9cc38f2be5f4f1) or cherry-pick [this](https://github.com/ngoquang2708/android_system_core/commit/6d253558fe441b4886e503e77ac53f83313998bd).

**Comment by ngoquang2708** [comment]
Commit bbc01d8
