### ISSUE TITLE
cm-12.1: Random reboots when using mobile data for too long (Beta 3)

### ISSUE THREAD

**Issue by diepquynh** [ngoquang2708/android_device_samsung_vivalto3gvn#39]
Again, users complaints

Off-topic: Did you retire bro?

**Comment by ngoquang2708** [comment]
Maybe the phone is overheated because of OC kernel + mobile data use a a lot of power.

**Comment by ngoquang2708** [comment]
Good news
![screenshot_20160522-040810](https://cloud.githubusercontent.com/assets/9676278/15454695/452ebb9a-206a-11e6-899f-fdf96ec2424d.png)
![screenshot_20160522-040829](https://cloud.githubusercontent.com/assets/9676278/15454696/4534605e-206a-11e6-8805-872f1a90701a.png)

But crash every where, you known :)

**Comment by diepquynh** [comment]
Wow, good work bro :D
At least it booted. Currently, we're all "fake" retired, so let's surprise people by a thread :D

**Comment by diepquynh** [comment]
But, what about the soft keys?

**Comment by ngoquang2708** [comment]
Don't ask about the soft keys! Are you kidding me?!!

**Comment by ngoquang2708** [comment]
:D

**Comment by diepquynh** [comment]
Vibrator died :D

**Comment by ngoquang2708** [comment]
What?

**Comment by diepquynh** [comment]
My phone's vibrator has died

**Comment by ngoquang2708** [comment]
Did you kill it :D

**Comment by diepquynh** [comment]
Nope :D
My brother plays games with the phone, and he got it pulled out from his wet hand while running, so.....

**Comment by diepquynh** [comment]
Ok, how was the progress with CM13?
Any important news?

**Comment by ngoquang2708** [comment]
Trying to fix the radio first.

**Comment by diepquynh** [comment]
Bro, IDK why people complaints a lot about Beta 3
Even installed beta 2 boot.img they still having random reboots, espically when they using mobile data
Can you remake it? :D
Beta 3 just have dlmalloc() impl for ART, updated sources (no need), some WITH_DEXPREOPT flags and removed "--block" parameters from build/core/Makefile for easy modding

Maybe my /home partition is corrupted

**Comment by ngoquang2708** [comment]
Ok, I will build new one

**Comment by koquantam** [comment]
Wait, classes.dex still being relocated to /data/dalvik-cache

**Comment by koquantam** [comment]
Bro, you missed this flag
`WITH_DEXPREOPT_COMP := false`
