### ISSUE TITLE
cm-13.0: MTP not work

### ISSUE THREAD

**Issue by ngoquang2708** [ngoquang2708/android_device_samsung_vivalto3gvn#40]

**Comment by diepquynh** [comment]
Confirmed

**Comment by diepquynh** [comment]
MTP works, but disabled by default. Touch the "USB for charging" on the notifications bar

**Comment by ngoquang2708** [comment]
OMG, just like the Bluetooth file transfer case :)

**Comment by ngoquang2708** [comment]
`It is not an error, you just didn't turn it on!`

**Comment by diepquynh** [comment]
LOL, great joke :D
I've heard this meme for tons of times
