### ISSUE TITLE
cm-13.0: audio not work

### ISSUE THREAD

**Issue by ngoquang2708** [ngoquang2708/android_device_samsung_vivalto3gvn#41]
Audio is not work because the audio module cannot access `/dev/snd/controlC%d` due to permission denies. Need to find out what service load audio module and set a proper user or group for it. My first guess is `mediaserver`, but it already had `system` group, which is `/dev/snd/controlC%d` has. Don't know why audio module cannot access it though.

**Comment by ngoquang2708** [comment]
Working now with this 71d544bfe690c8cec1699e4988bea30358a0b28a. Need a better solution.

**Comment by ngoquang2708** [comment]
Fixed by https://github.com/ngoquang2708/android_system_core/commit/838a95a878be4b1f708fff64a7edba3c57e09057.

**Comment by ngoquang2708** [comment]
Stop working again after rebase upstream.

**Comment by ngoquang2708** [comment]
@koquantam This thing look like crap again :(

**Comment by diepquynh** [comment]
We're back with CM-11.0 :D

**Comment by diepquynh** [comment]
Did you tried REmarking mediaserver as root user?

**Comment by ngoquang2708** [comment]
OMG, sound back again. I hate it so much.

**Comment by diepquynh** [comment]
How? Randomly?

**Comment by ngoquang2708** [comment]
Recompile the source again, and it work again. Don't know why :(

**Comment by ngoquang2708** [comment]
Found some interesting things. We didn't use `audio_policy.*.so` at all since CM-12.1. Deleted all of them, and sound stills working.
Then, I discovered that, CM-12.1 use `libaudiopolicymanagerdefault.so`. So we should focus on them.
The source is located at `frameworks/av/services/audiopolicy`.

**Comment by diepquynh** [comment]
Lol, I known that lib :D but thought it was in hardware frameworks

**Comment by ngoquang2708** [comment]
Found some thing interesting. I can route audio from mic to speaker by `echo 1,2,7 > /dev/pipe/mmi.audio.ctrl`, route to earpiece by `echo 1,1,7 > /dev/pipe/mmi.audio.ctrl`. I don't known the way android route app's sound to speaker. Any ideas?
@koquantam 
@corphish

**Comment by ngoquang2708** [comment]
Seem this fix our issue completely https://github.com/ngoquang2708/android_device_samsung_vivalto3gvn/commit/0f9e32856267bac253ccb3bd07dc869604177464.
I try 1 clean build with that flag enabled and another clean build with that flag disabled to confirm it.
@koquantam If you have time, pleases confirm this.

**Comment by diepquynh** [comment]
OK, CM12.1 is done with me, now I'm doing for our vivalto

**Comment by diepquynh** [comment]
Making clean build now

**Comment by diepquynh** [comment]
This situation was just like RIL :D
One BoardConfig flag solves all

**Comment by ngoquang2708** [comment]
Hope so :)

**Comment by diepquynh** [comment]
Confirmed

**Comment by diepquynh** [comment]
I think we have already known this happen while reading the commit message from your referenced commit

**Comment by diepquynh** [comment]
Hmm... somehow audio doesn't work again o.O

**Comment by ngoquang2708** [comment]
Aggh, just happened to me with the last build, again. Doing a clean build, again :(

**Comment by ngoquang2708** [comment]
Since CM-11.0, this audio issue is always suck.

**Comment by diepquynh** [comment]
Totally sucks

**Comment by ngoquang2708** [comment]
But at least it works for you the first time, right :)

**Comment by diepquynh** [comment]
I guess, this is our problem
`06-28 11:50:49.637   251   251 E TinyAlsaUtils: open snd control failed.`

**Comment by ngoquang2708** [comment]
~~I just restart an audio is working again, what the heck!~~ FALSE ALARM~

**Comment by diepquynh** [comment]
Oh you've told in description :D

**Comment by ngoquang2708** [comment]
About this:

```
06-28 12:01:30.284   148   148 E TinyAlsaUtils: open snd control failed: No such file or directory
```

I have it too, it just cannot open one card, ~~we have 3~~ we have 4:

```
06-28 12:01:30.284   148   148 I audio_hw_primary: s_tinycard = 0, s_vaudio = -1,s_voip = 2, s_bt_sco = 3,s_vaudio_w is 1
```

**Comment by diepquynh** [comment]
Should we use again the mediaserver hack?

**Comment by ngoquang2708** [comment]
`mediaserver` already had the right permission to access `/dev/snd/*`. The fact is that audio work for some times.
But we should try.
About my previous comment about sound working again after reboot, sorry, false alarm. I am using my other build that with audio working, not my latest build :(

**Comment by ngoquang2708** [comment]
Can I ask you that your audio stop working with different builds or with the same build?

**Comment by diepquynh** [comment]
It work for the first time in the last build from yesterday, then stopped working after ONE RESTART LOL

**Comment by ngoquang2708** [comment]
OK, one more clue.

**Comment by diepquynh** [comment]
That's all :D

**Comment by diepquynh** [comment]
If we have to touch mediaserver again, then I think it's init problem (system/core)

Edit: The hack isn't working anymore LOL

**Comment by ngoquang2708** [comment]
Try this [magic.diff.zip](https://github.com/ngoquang2708/android_device_samsung_vivalto3gvn/files/336978/magic.diff.zip).

**Comment by diepquynh** [comment]
Is that real magic? :D

**Comment by ngoquang2708** [comment]
Yes

**Comment by diepquynh** [comment]
OK, gonna try with my Core Prime :D

Seems everything in our tree works with it

**Comment by ngoquang2708** [comment]
Do not need to make a clean build, just rebuild `audio.primary.scx15.so`.

**Comment by diepquynh** [comment]
Right

**Comment by diepquynh** [comment]
Btw, how to rebuild a blob only?
Just "mka bacon" or something else?

**Comment by ngoquang2708** [comment]
cd to that audio dir
then `mm`

**Comment by ngoquang2708** [comment]
Use `mmp`, it will push to your phone automatically using `adb`.

**Comment by diepquynh** [comment]
Wow, thanks

**Comment by ngoquang2708** [comment]
You never read CM's Wiki, right :)

**Comment by ngoquang2708** [comment]
Tons of great things there.

**Comment by diepquynh** [comment]
I just know basic parameters, like mka :D

**Comment by ngoquang2708** [comment]
I've read it, and I missed that `mka`, until you told me.

**Comment by diepquynh** [comment]
LOL

**Comment by diepquynh** [comment]
OK, confirmed this magic thingy :D

**Comment by diepquynh** [comment]
Now I can watch YouTube everyday :D

**Comment by ngoquang2708** [comment]
Seem we lost the audio equalizer, make sound seem... I don't know which word to describe it, like cracked... :)

**Comment by ngoquang2708** [comment]
I had that issue since CM-11.0, not happen in CM-12.1, then it come back in CM-13.0.

**Comment by diepquynh** [comment]
It seems OK for me, even watching videos
Nope, normal than OK

But, the audio is louder than normal

**Comment by ngoquang2708** [comment]
Yes, listen to some music with loud bass, it will kill your speaker :)

**Comment by diepquynh** [comment]
Should we close this issue?

**Comment by ngoquang2708** [comment]
No no... NOOO

**Comment by ngoquang2708** [comment]
I am afraid of doing it :(

**Comment by diepquynh** [comment]
Ok, it's really our pain for long time, so nope :D
But hey, after restarting audio still works

**Comment by corphish** [comment]
OT
SGV has a flashlight?

**Comment by PhantomAssassin12** [comment]
@corphish Yeah SGV has it

**Comment by corphish** [comment]
Good for you
Camera already works right?

Looks like flashlight is a must if you want to run MM on it.

**Comment by diepquynh** [comment]
@corphish 
Also auto-focus is very fast

**Comment by PhantomAssassin12** [comment]
Can i have that audio fix...?

**Comment by ngoquang2708** [comment]
@PhantomAssassin12  This is just temporary [audio.primary.scx15.so.zip](https://github.com/ngoquang2708/android_device_samsung_vivalto3gvn/files/337131/audio.primary.scx15.so.zip).

**Comment by ngoquang2708** [comment]
@PhantomAssassin12 Please wait for next build.

**Comment by ngoquang2708** [comment]
Look at this:
![screenshot from 2016-06-28 22-36-20](https://cloud.githubusercontent.com/assets/9676278/16421953/db543554-3d80-11e6-875d-ba19bf04a0db.png)
This is kmsg, on the left is of CM-12.1, on the right is of CM-13.0.

**Comment by ngoquang2708** [comment]
Look at the codes of `system/core/init/devices.c(pp)*`, the code section that load firmware has changed!

**Comment by ngoquang2708** [comment]
Fixed.
REF:
- https://github.com/ngoquang2708/android_device_samsung_vivalto3gvn/commit/65a1216bdd4f981c68ce8625b73c2d6ae8c565b4
- https://github.com/ngoquang2708/android_vendor_samsung_vivalto3gvn/commit/efa9b508b60192a6e94ff0abf8ab93da807566d2
- https://github.com/ngoquang2708/android_hardware_samsung_sprd-common/commit/cfb0d9b86623a1a7f165f68d249b058ca35d5e41

**Comment by diepquynh** [comment]
Again, one simple thing solves the huge problem :v
IDK if this will happen again in Nougat

**Comment by ngoquang2708** [comment]
I hope not :)
