### ISSUE TITLE
cm-13.0: Apps can't be installed

### ISSUE THREAD

**Issue by diepquynh** [ngoquang2708/android_device_samsung_vivalto3gvn#43]
Just the apps out of Play Store

**Comment by koquantam** [comment]
Just the apps out of Play Store

**Comment by ngoquang2708** [comment]
Does "in of Play Store" need [this](https://github.com/koquantam/android_device_samsung_vivalto3gvn/commit/8d224f33c4c7cb03ad4518b73abf80ba9e1f7c06).

**Comment by diepquynh** [comment]
Google services just FCs, at least with me

**Comment by diepquynh** [comment]
Solved https://github.com/koquantam/android_device_samsung_vivalto3gvn/commit/eb3fd331a70be0921f71d7a826ea2c8961f7debb
