### ISSUE TITLE
cm-13.0: Screencast doesn't work

### ISSUE THREAD

**Issue by diepquynh** [ngoquang2708/android_device_samsung_vivalto3gvn#45]
It's screen recorder btw. Tap record would freeze the system, and will automatically do a soft reboot after some minutes

**Comment by ngoquang2708** [comment]
Confirmed.

**Comment by ngoquang2708** [comment]
I can make screencast with [this](https://github.com/ngoquang2708/android_device_samsung_vivalto3gvn/commit/67ad84476b4044701a869c51582ae744bdd0fab2). Need to find the proper way to fix this.

**Comment by ngoquang2708** [comment]
Fixed.
REF:
- https://github.com/ngoquang2708/android_device_samsung_vivalto3gvn/commit/67ad84476b4044701a869c51582ae744bdd0fab2
- https://github.com/ngoquang2708/android_hardware_samsung_sprd-common/commit/ff6828ecf6e83f04dbc30717368c0eef663da067
