### ISSUE TITLE
Camera not work with new source code

### ISSUE THREAD

**Issue by ngoquang2708** [ngoquang2708/android_device_samsung_vivalto3gvn#5]

**Comment by diepquynh** [comment]
Please close this, as it's working now

**Comment by ngoquang2708** [comment]
Did you test it? I means compile the source codes, not use the blobs.

**Comment by diepquynh** [comment]
Of course, because stock blobs causes "Cannot connect to camera" bug

**Comment by ngoquang2708** [comment]
I don't know what you means. We ARE using stock blobs. I disabled the camera source already.

**Comment by diepquynh** [comment]
Umm... in CM12.1 bro

**Comment by diepquynh** [comment]
Ok, i think again
When compiling, i forgot to comment out the stock blob, so still unconfirmed now :D

**Comment by ngoquang2708** [comment]
These lines

```
# Camera
PRODUCT_PACKAGES += \
    camera.scx15 \
    camera2.scx15
```

in `device_vivalto3gvn.mk` do nothing right now!

**Comment by diepquynh** [comment]
Lots of compile error bro

**Comment by diepquynh** [comment]
A real pain in the 4$$ fixing that

**Comment by ngoquang2708** [comment]
Living with blobs for now. Trying fixing video.

**Comment by diepquynh** [comment]
Btw, going to compile CM13
Not sure i have enough RAM or not to build the ROM with prebuilt chromium

**Comment by ngoquang2708** [comment]
Search around to find someone compiled it :D

**Comment by diepquynh** [comment]
Yeah, the prebuilt chromium

**Comment by diepquynh** [comment]
I think, our sensor codes aren't in the camera source. Check logcat and you'll find it
