### ISSUE TITLE
common: STK doesn't work

### ISSUE THREAD

**Issue by diepquynh** [ngoquang2708/android_device_samsung_vivalto3gvn#51]
Tested on both core33g and vivalto. If you choose any option from the menu (except choosing SIM), STK stuck and continuously spinning

**Comment by ngoquang2708** [comment]
Tested with single SIM. Not tested with dual SIM yet.

https://youtu.be/YBuqXccwNlo

**Comment by PhantomAssassin12** [comment]
Confirmed

**Comment by ngoquang2708** [comment]
What do you mean? Are you affected?

**Comment by PhantomAssassin12** [comment]
Yeah tested on dual sim card

**Comment by diepquynh** [comment]
Hmm... I got some results after testing with different operators

The STK actually work for some network operators, in our country are Vinaphone and Mobifone, but not Viettel. Maybe VT has different way of sending STK signals. I'll check logcat with this

**Comment by ngoquang2708** [comment]
I tested it on dual-sim. No issue.
@koquantam @PhantomAssassin12 Anyone stills affect by this issue? Should I close this?

**Comment by diepquynh** [comment]
Ok, pls close this
