### ISSUE TITLE
cm-13.0: FMRadio

### ISSUE THREAD

**Issue by ngoquang2708** [ngoquang2708/android_device_samsung_vivalto3gvn#52]
I've patched `hardware/libhardware`, `system/bt`, `packages/apps/Bluetooth` and `packages/apps/FMRadio` based on @mickybart repos.
Now I can loop though radio stations around me by observe the freq indicator. But some how the device cannot route the audio to speaker or to headset.
In this [initAudioRecordSink](https://github.com/ngoquang2708/android_packages_apps_FMRadio/blob/cm-13.0/src/com/android/fmradio/FmService.java#L1360-L1365) method, it failed to find the device for `MediaRecorder.AudioSource.RADIO_TUNER` source.

**Comment by ngoquang2708** [comment]
@mickybart Do you have any ideas?

**Comment by diepquynh** [comment]
@ngoquang2708 
Bro, should we use BRCM FM radio source from FFOS git?

**Comment by ngoquang2708** [comment]
Where is it?

**Comment by diepquynh** [comment]
https://git.mozilla.org/?p=external/sprd-aosp/vendor/sprd/partner.git;a=tree;f=brcm/libfm-brcm;h=6d6daa39e1cc38865d9d10348131bc8a7679b6ad;hb=refs/heads/sprdroid4.4

**Comment by diepquynh** [comment]
We have other radio sources too, like trout. I've just confused which one should we use
There also have FM package source, which is nice

**Comment by ngoquang2708** [comment]
Thanks.

**Comment by ngoquang2708** [comment]
No longer supported.
