### ISSUE TITLE
WiFi-Direct does not work

### ISSUE THREAD

**Issue by ngoquang2708** [ngoquang2708/android_device_samsung_vivalto3gvn#54]
`wpa_supplicant` cannot initialize the `p2p0` interface. It says `No such device` while ~~`ipconfig -a`~~ `ifconfig -a`shows there is `p2p0` interface.

**Comment by diepquynh** [comment]
It must be "ifconfig" instead of ipconfig. It's for Windows only
And that p2p0 device is for USB tethering. Don't you see "Ethernet" there?
![screenshot_20160722-180741](https://cloud.githubusercontent.com/assets/13411810/17055483/3c6bf336-5037-11e6-895b-137fd614f7ce.png)

**Comment by diepquynh** [comment]
Weird is we get "No such device" here

**Comment by ngoquang2708** [comment]
OK, I misspelled it. Did you compare it with wlan0 (when wifi is off)? They
are the same!

2016-07-22 18:08 GMT+07:00 Nguyễn Tuấn Quyền notifications@github.com:

**Comment by ngoquang2708** [comment]
I ran `wpa_supplicant -i p2p0 -Dnl80211 -c /data/misc/wifi/p2p_supplicant.conf` to test it. With `-i wlan0`, it works, with `-i p2p0`, it does not.

**Comment by diepquynh** [comment]
OK, my mistake :D

**Comment by koquantam** [comment]
Look at our init.wifi.rc, p2p_supplicant service use wlan0 interface lol

**Comment by ngoquang2708** [comment]
WiFi-Direct is working now. Maybe CM's repo is updated with changes that make it works.

**Comment by ngoquang2708** [comment]
![screenshot_20160728-214803](https://cloud.githubusercontent.com/assets/9676278/17217047/38e8f396-550d-11e6-8b0d-007f41e81ef0.png)
