### ISSUE TITLE
Cannot get pass Setup Wizard on clean install

### ISSUE THREAD

**Issue by ngoquang2708** [ngoquang2708/android_device_samsung_vivalto3gvn#56]
On clean install, we cannot click any button.

**Comment by ngoquang2708** [comment]
The current workaround is install older build, set it up then flash the latest build without factory reset.

**Comment by thanhthuy89** [comment]
bác tạo cho e cái patch cho beta1update 1 ko bị screen flickering dc ko?. tuy am thanh rè nhung co the fix bang audio fx dc.am thanh to hon bản beta 2 nhieu tieng anh yeu nen cho e ghi tam it tieng viet

**Comment by PhantomAssassin12** [comment]
Yeah its like locking the setup and the status pulled down and i can go settings without setting it up. Btw not whole screen but haft of it down side.

**Comment by ngoquang2708** [comment]
@thanhthuy89 Gải nén file này rồi copy vô `/system/lib/`: [libhwui.so.zip](https://github.com/ngoquang2708/android_device_samsung_vivalto3gvn/files/386179/libhwui.so.zip).

**Comment by ngoquang2708** [comment]
@thanhthuy89 Âm thanh to qúa nên nó bị rè là phải.

**Comment by thanhthuy89** [comment]
Lúc cài beta2 xong thay lỗi quay lai update1 flash xong quen gapp khoi dong lai vao twrp wipe data/factory flash gapp van ko bi đơ thanh trạng thái,sau lan nay lam vay kéo thang trai thái xuong nhung ko kéqo bật tắt nhanh dc la sau vay bac Quang

**Comment by ngoquang2708** [comment]
@thanhthuy89 Bạn có backup beta1update1 ko, restore nó lại đi. Bạn không flash Gapps sau khi flash rom nên bị lỗi gì rồi.

**Comment by thanhthuy89** [comment]
Noi thiet nhe minh flash beta1 up1 ca may chuc lan xong deu wipe data nhubg ko bi vay? Sau gio flash xong wipe data cai le keo xuong ko dc

**Comment by ngoquang2708** [comment]
@thanhthuy89 Neu co y dinh cai lai tu dau thi nen wipe system+data+cache.

**Comment by thanhthuy89** [comment]
Bạn co thuong len gmail ko ? Iien lac cach nao tien va nhanh dc ko? Co bi gi minh hoi

**Comment by thanhthuy89** [comment]
Luc nao cai rom minh ko wipe full,moi dung odin up stock lai so stock lỗi,

**Comment by ngoquang2708** [comment]
I don't know what cause this issue yet but after sync the repo, the problem is gone.
