### ISSUE TITLE
data movil not working

### ISSUE THREAD

**Issue by mfenano** [ngoquang2708/android_device_samsung_vivalto3gvn#58]
hello my model is smg313ml rom version of the original cell is achieved G313MLUBS0APE3_G313MLUUB0AOJ1_G313MLUBU0AOJ1_HOME.tar install your cyanogenmod13 beta 2 without problems the problem is they do not work mobile data 3g wifi only hope can repair this error in its new version

**Comment by diepquynh** [comment]
It's baseband related problem I guess, because someone reflashed old baseband for SM-G313ML and mobile data works

Anyway, don't make an issue here, unless you're having contributions to our development, and on every issue, please provide logcat

**Comment by ngoquang2708** [comment]
@mfenano Read through CM13 for Galaxy V thread on XDA forum, you will found workaround for mobile data. Basically, you will have to flash a specific version of your baseband. Detailed information there.

**Comment by mfenano** [comment]
what baseband is recommender for flash this rom?
