### ISSUE TITLE
The audiofx is not working

### ISSUE THREAD

**Issue by ghost** [ngoquang2708/android_device_samsung_vivalto3gvn#59]
It says not available when using speaker while I actually plugged in the headset, how is that possible?

**Comment by ngoquang2708** [comment]
Confirmed.

**Comment by diepquynh** [comment]
@ngoquang2708 
This thing... I've reported a very long time ago, since CM11, but you said it's working LOL

**Comment by ngoquang2708** [comment]
Fixed by https://github.com/ngoquang2708/android_device_samsung_vivalto3gvn/commit/5be9eb1ae96cfa39011abe8a60ec04210697267a.
