### ISSUE TITLE
Recent button Spam

### ISSUE THREAD

**Issue by PhantomAssassin12** [ngoquang2708/android_device_samsung_vivalto3gvn#61]
Keeps Spamming the Recent button at 29% of battery and after it shut of.

**Comment by PhantomAssassin12** [comment]
@ngoquang2708 do you have this issue?

**Comment by ngoquang2708** [comment]
What is "spam" means here? Spamming logcat?

**Comment by PhantomAssassin12** [comment]
Keeps pressing the recently button

**Comment by PhantomAssassin12** [comment]
I don't touch the screen but still touching the recently button itself.

**Comment by ngoquang2708** [comment]
Is you screen broken?

**Comment by ngoquang2708** [comment]
I got that too, but my screen is broken so though that was the reason.

**Comment by PhantomAssassin12** [comment]
no! my screen is clean don't have any scratches but i have tempered glass protector is this the problem?

**Comment by PhantomAssassin12** [comment]
how did you fixed it?

**Comment by ngoquang2708** [comment]
I cannot. I just remove /system/usr/keylayout/ist30xx_ts_input.kl and add
qemu.hw.mainkeys=0 to build.prop to use soft-navbar.

2016-07-31 16:17 GMT+07:00 PhantomAssassin12 notifications@github.com:

**Comment by PhantomAssassin12** [comment]
Okay.

**Comment by PhantomAssassin12** [comment]
btw can i have your latest build?
