### ISSUE TITLE
Cannot use LD_SHIM_LIBS when SELinux is enforcing

### ISSUE THREAD

**Issue by ngoquang2708** [ngoquang2708/android_device_samsung_vivalto3gvn#62]

**Comment by diepquynh** [comment]
Wow, it booted with Enforcing?
I saw bunch of commits there

**Comment by ngoquang2708** [comment]
It cannot help if we cannot use LD_SHIM_LIBS :)

**Comment by ngoquang2708** [comment]
Fixed by https://github.com/ngoquang2708/android_device_samsung_vivalto3gvn/commit/8273f3ac32d18ab57c75a2df7d13ee2e7dc71c34.
