### ISSUE TITLE
Randomly lost mobile network on Enforcing SELinux mode

### ISSUE THREAD

**Issue by ngoquang2708** [ngoquang2708/android_device_samsung_vivalto3gvn#63]

**Comment by thanhthuy89** [comment]
co cach nao fix an recent app ma lag voi xiu moi hien cac ung dung ra ko bac Quang

**Comment by ngoquang2708** [comment]
@thanhthuy89 ROM gốc nhanh lắm đó bạn :)

**Comment by thanhthuy89** [comment]
minh ko chê... chi la hoi ban co cach lam no nhanj xiu ko thoi

**Comment by ngoquang2708** [comment]
Minh khong noi la ban che. Nhung su that la vay ma :D

**Comment by ngoquang2708** [comment]
SGV qua yeu.

**Comment by thanhthuy89** [comment]
beta3 nay em.youtobe coi ko lag. chi co cai la thanh trang thai keo len xuong giat voi recent app cham.... hoi nay choi 3g nong ran may cai tu khoi dong lai... chua biet phai bi reboot do 3g ko nua

**Comment by thanhthuy89** [comment]
giup minh dc ko ?

**Comment by ngoquang2708** [comment]
Fix with these commits:
- 61b076160c3d063b9c32724fff2030ad7230e857
- 204a6730fa20ddc12695ca50c66c03c2e14df9eb
- 2c44f6893958a68958caa940e2fb493bab290222
- 13af2e19a7267bf3406925f1db02bb4900f90337
- dbe53794c2228bbed313115acdc7f1f27d226e89
- 851a0fb40f6a7bcca841980081ea2c48b29bff1b
