### ISSUE TITLE
SIM cards manager shows wrong SIM slot number

### ISSUE THREAD

**Issue by ngoquang2708** [ngoquang2708/android_device_samsung_vivalto3gvn#65]
When I put only one SIM to the phone on the 2nd SIM slot, SIM manager shows the SIM in the 1st SIM slot.

**Comment by diepquynh** [comment]
Workaround: Restart RIL daemon

**Comment by diepquynh** [comment]
Btw, is git down for you? I'm stuck on loading for almost the whole time

**Comment by ngoquang2708** [comment]
The AAG cable is broken :) Do not you read the news?

**Comment by diepquynh** [comment]
Ok now I know. Maybe Spreadtrum Shark ate the cable 😂

**Comment by ngoquang2708** [comment]
That is so true!

**Comment by diepquynh** [comment]
Here bro. It's a 13,5MB patch
https://drive.google.com/open?id=0BzWikRa31-8qUkFwQUExLThfbHM

**Comment by ngoquang2708** [comment]
Thank you.
