### ISSUE TITLE
Random reboot when install the boot.img

### ISSUE THREAD

**Issue by ghost** [ngoquang2708/android_device_samsung_vivalto3gvn#66]
The rom is great but with the new selinux enforcing mode, some of my apps cant grant root access, so I decided to install the boot.img, it's fix the app that cant access root because the selinux is now permissive. But I have new problem, random reboot, it never happen if I dont install the boot.img

**Comment by ngoquang2708** [comment]
Can I have kmsg log?

2016-08-06 22:47 GMT+07:00 hendrulll notifications@github.com:

**Comment by ngoquang2708** [comment]
Please take it with SELinux Enforcing.

2016-08-06 22:51 GMT+07:00 Quang Ngô ngoquang2708@gmail.com:

**Comment by ghost** [comment]
What is kmsg log? how can I do that? Btw sorry I'm newbie

**Comment by ngoquang2708** [comment]
Run adb shell cat /dev/kmsg > log.txt, open your app, do stuffs, then press
ctrl+c in your terminal. Take your log.txt here.

**Comment by ghost** [comment]
It says cant create log.txt: read only file system

**Comment by ngoquang2708** [comment]
OK, run this:

adb shell dmesg

2016-08-06 23:10 GMT+07:00 hendrulll notifications@github.com:

**Comment by ghost** [comment]
sh: adb: not found

**Comment by ngoquang2708** [comment]
OK, if you run Terminal in you phone, do this.
Open Terminal
cd /storage/emulated/0/
su
dmesg > log.txt

2016-08-06 23:13 GMT+07:00 Quang Ngô ngoquang2708@gmail.com:

**Comment by ngoquang2708** [comment]
That log.txt will be iin your internal storage.

2016-08-06 23:19 GMT+07:00 Quang Ngô ngoquang2708@gmail.com:

**Comment by ghost** [comment]
[log.txt](https://github.com/ngoquang2708/android_device_samsung_vivalto3gvn/files/405078/log.txt)

**Comment by ngoquang2708** [comment]
Thank you. I will investigate it.

**Comment by ghost** [comment]
Yea, hope you can fix it soon. Thanks for always available bruh

**Comment by thanhthuy89** [comment]
Use selinux mod changer.apk can chance between enforcing and permissive

**Comment by ngoquang2708** [comment]
Not exists any more in my latest build. I will release it soon.
