### ISSUE TITLE
Cannot switch mobile data without reset the RIL

### ISSUE THREAD

**Issue by ngoquang2708** [ngoquang2708/android_device_samsung_vivalto3gvn#70]
There are changes in `DcSwitchStateMachine` since CM-12.1. I think those changes cause this issue but I am not sure. Point it out here to have a clue for more investigation.

**Comment by diepquynh** [comment]
You mean soft reboot?

**Comment by ngoquang2708** [comment]
No soft reboot but I must reboot to switch mobile data.

**Comment by diepquynh** [comment]
Sorry for not asking properly, but I mean do you have to do a soft reboot to switch mobile data SIM or a hard reboot?

This was existed since CM11, not CM12.1

**Comment by ngoquang2708** [comment]
AirplaneMode and HardReboot works, SoftReboot does'nt. It means I have to
fully reset the modem.

2016-08-14 11:40 GMT+07:00 Nguyễn Tuấn Quyền notifications@github.com:

**Comment by thanhthuy89** [comment]
bác quang oi... toi da test cai nay la co 100%.. khi toi choi game online 3g lien tuc bi doi thang 2g.... stock thi ko co.. mong bac fix som

**Comment by ngoquang2708** [comment]
Fixed by commit https://github.com/ngoquang2708/android_device_samsung_vivalto3gvn/commit/555ab6cfbb052d2a42028b3443644dee3083149c.
