### ISSUE TITLE
Cannot built the kernel with "arm-linux-androideabi-" toolchain

### ISSUE THREAD

**Issue by ngoquang2708** [ngoquang2708/android_device_samsung_vivalto3gvn#72]

**Comment by diepquynh** [comment]
What does the compiler gives?

**Comment by ngoquang2708** [comment]
I can built with cm-13, but there is some linker warning and I cannot boot
that kernel. I cannot build the kernel at all in cm-14.0. It throws errors
when parsing __PASTE macro in include/linux/compiler-gcc4.h which caused
when building sound/soc/sprd/dai/sprd-pcm.c, when expand MODULE_ALIAS macro.

2016-08-28 23:08 GMT+07:00 Nguyễn Tuấn Quyền notifications@github.com:

**Comment by diepquynh** [comment]
LOL try using other compiler, like Linaro 5.1 or sth
Or use my compiler-gcc.h in my grandprimeve3g kernel source, as in 3.10.102, compiler-gccX are deprecated

**Comment by ngoquang2708** [comment]
OK, I will test it later. Using arm-eabi-4.8 currently.

2016-08-28 23:15 GMT+07:00 Nguyễn Tuấn Quyền notifications@github.com:

**Comment by ngoquang2708** [comment]
Fixed by commit https://github.com/ngoquang2708/android_kernel_samsung_vivalto3gvn/commit/563da18bca372b290b2247975161836a203b3efe.
