### ISSUE TITLE
No mobile data

### ISSUE THREAD

**Issue by ngoquang2708** [ngoquang2708/android_device_samsung_vivalto3gvn#76]

**Comment by dragonroad99** [comment]
Sir can i test Aosp 6.0 please.

**Comment by ngoquang2708** [comment]
@fadhilm293 Here you are http://www.mediafire.com/download/12okiz199o29v2v/aosp-6.0-vivalto3gvn.zip.

**Comment by ngoquang2708** [comment]
@fadhilm293 Install it with this https://github.com/ngoquang2708/android_device_samsung_vivalto3gvn/files/462135/twrp2.img.zip.

**Comment by dragonroad99** [comment]
Thanks sir,Btw is there any other bug?

**Comment by ngoquang2708** [comment]
@fadhilm293 You tell me :)

**Comment by dragonroad99** [comment]
List of bug that i found:
- Baseband unknow
- systemui and com.android.phone always force close
- some application force close
- can't detect sim card.

**Comment by ngoquang2708** [comment]
Yeah, that is it! The goal is not to build AOSP 6 but 7.

**Comment by dragonroad99** [comment]
Okay,but please fix bug on this rom because this rom very smoothly.

**Comment by ngoquang2708** [comment]
I would do if I have time. But I don't. So sorry that I can't.

2016-09-18 19:06 GMT+07:00 fadhilm293 notifications@github.com:

**Comment by dragonroad99** [comment]
Okay,please tell me if the bug has been fixed,you are the best.

**Comment by dragonroad99** [comment]
If not,please let me know how to fix that bug.

**Comment by ngoquang2708** [comment]
I have not identified the causes of those bugs so I can't tell you.

**Comment by ngoquang2708** [comment]
Fixed by these commits: https://github.com/ngoquang2708/android_device_samsung_vivalto3gvn/commit/40b4629186d58ccd540b4d5f44b0aa06bb4b5179 https://github.com/ngoquang2708/android_device_samsung_vivalto3gvn/commit/3773ed9e1e46515feafc79315265ca1c63f16612.

**Comment by thanhthuy89** [comment]
i can't flash aosp 6.0 by twrp ( 3.0.2.0 & 2.8.5.0) error . please repair aosp 6.0

**Comment by dragonroad99** [comment]
I try and find bug on aosp6
Among others :
- Can't play video videos in stock gallery and Third-party applications
- The camera upside down after taking a picture.

Sorry for bad English.

**Comment by dragonroad99** [comment]
Sorry miss, I tried it on AOSP Beta 1.

**Comment by ngoquang2708** [comment]
@fadhilm293 Thank you. I will check it.

**Comment by dragonroad99** [comment]
Sir,I found another bug.
- Setup wizard has force close after Sim card detected and set up sim card.

Sorry for bad English.😁

**Comment by ngoquang2708** [comment]
@fadhilm293 What is your phone variant, H, HZ or ML?

**Comment by dragonroad99** [comment]
My Phone is SM-G313HZ.

**Comment by ngoquang2708** [comment]
I have the same variant as yours, but don't encounter those issues. Please
provide logcat after each of those issues happened, then open new issue (on
github) for each of them and attach logcat there. I would greatly
appreciate.

2016-09-25 20:39 GMT+07:00 fadhilm293 notifications@github.com:

**Comment by dragonroad99** [comment]
@ngoquang2708 Here is logcat 
http://upfile.mobi/VKlTgEJwLIv

**Comment by dragonroad99** [comment]
@ngoquang2708 please give me file to fix video codec and Hw rendering,because if i'am use Sw rendering,its so sluggish for playing video.

**Comment by ngoquang2708** [comment]
@fadhilm293 N ate all of my time, I do not have time for M. Sorry.
