### ISSUE TITLE
Error when building aosp 7.0 from source

### ISSUE THREAD

**Issue by xdaHicham03** [ngoquang2708/android_device_samsung_vivalto3gvn#79]
`make: *** No rule to make target « out/target/product/vivalto3gvn/obj/STATIC_LIBRARIES/libhealthd.scx15_intermediates/export_includes », needed by « out/target/product/vivalto3gvn/obj/EXECUTABLES/recovery_intermediates/import_includes ». Stop.`

**Comment by ngoquang2708** [comment]
Set the right value of flag `BOARD_HAL_STATIC_LIBRARIES` for your board in `BoardConfig.mk`.

**Comment by xdaHicham03** [comment]
But what will I change in `BOARD_HAL_STATIC_LIBRARIES`?

**Comment by ngoquang2708** [comment]
Change it to your static health module name or just remove that flag.

2016-09-24 18:58 GMT+07:00 Hicham03 notifications@github.com:
