### ISSUE TITLE
Error libs engmode

### ISSUE THREAD

**Issue by cleverior** [ngoquang2708/android_device_samsung_vivalto3gvn#8]
device/samsung/vivalto3gvn/libs/engmode/iwnpi/Android.mk:25: **\* my-dir must be called before including any other makefile..  Stop.

**Comment by ngoquang2708** [comment]
Delete all comtents of engmode/Android.mk but keep the empty file, audio module just use some header from it, maybe I will do some cleanup later.

**Comment by cleverior** [comment]
OK.. lemme try it

**Comment by cleverior** [comment]
Thanks. It works.
