### ISSUE TITLE
FileManager cannot access external SD card even with root

### ISSUE THREAD

**Issue by ngoquang2708** [ngoquang2708/android_device_samsung_vivalto3gvn#84]

**Comment by PhantomAssassin12** [comment]
CMFileManager?
Btw I Had a issue when I try the aosp 6 my recovery has change any idea?

**Comment by PhantomAssassin12** [comment]
Can i test the latest CM14 build? Also?

**Comment by ngoquang2708** [comment]
I will release it soon. Please wait.

**Comment by PhantomAssassin12** [comment]
Okay but im stock in stock recovery in aosp 7 what is that?

**Comment by ngoquang2708** [comment]
I do not understand what you said.

2016-09-29 19:20 GMT+07:00 PhantomAssassin12 notifications@github.com:

**Comment by PhantomAssassin12** [comment]
Nvm.

**Comment by corphish** [comment]
Its a CM bug, will eventually be fixed

**Comment by ngoquang2708** [comment]
Some how, CMFileManager cannot list ```SDCARD/.android_secure``` folder (which I believe is created by older version of Android and still exists on my SDCARD). Delete that folder so that CMFileManager can access SDCARD.
