### ISSUE TITLE
No bluetooth

### ISSUE THREAD

**Issue by ngoquang2708** [ngoquang2708/android_device_samsung_vivalto3gvn#96]
Log: https://gist.github.com/ngoquang2708/07090ee739776252d26e6fd771b468fb

**Comment by diepquynh** [comment]
This is binderized bluetooth service, which is for binderized bluetooth HAL only
I haven't seen any bcm devices with binderized bluetooth HAL ready

Temporary just remove the service. Here with sc8830 BT works with legacy HAL

**Comment by ngoquang2708** [comment]
Thank for that info.

**Comment by ngoquang2708** [comment]
Fixed by commit https://github.com/ngoquang2708/android_device_samsung_vivalto3gvn/commit/bff7581166fea3905099774ea2f617be3ca9112c.
